services:
  db:
    image: mysql:12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/my.cnf


  app-back:
    build: ./api-uno/
    depends_on: db
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge


volumes:
  mysql_data: